stages:
  - build
  - test

build:
  stage: build
  script:
    - ln -s $(pwd) $GOPATH/src/$CI_PROJECT_NAME
    - go build
    - ls .
  tags:
    - go

test:
  stage: test
  script:
    - docker info
  tags:
    - docker
