before_script:
  - ln -s "${CI_PROJECT_DIR}/vendor/"* "${GOPATH}/src/"

after_script:
  - echo "after_script"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - go build -o hello main.go
    - docker build -t docker.gf.com.cn/hello .
    - docker push docker.gf.com.cn/hello
  tags:
    - eagle.build

test:
  stage: test
  script:
    - echo "test"
  tags:
    - eagle.build

deploy:
  stage: deploy
  script:
    - echo "deploy"
  tags:
    - eagle.build
