stages:
  - build

build:
  stage: build
  image: 'docker.gf.com.cn/docker-go'
  script:
    - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${CI_PROJECT_NAME}"
    - go build -o hello main.go
    - docker build docker.gf.com.cn/just4test/hello .
  tags:
    - docker
