stages:
  - build
  
services:
  docker.gf.com.cn/docker:1.12.6

build:
  stage: build
  image: 'docker.gf.com.cn/docker-go'
  script:
    - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${CI_PROJECT_NAME}"
    - docker version
  tags:
    - test
