stages:
  - build
  - test

build:
  stage: build
  image: 'docker.gf.com.cn/go:1.8.1'
  script:
    - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${CI_PROJECT_NAME}"
    - go build -o hello main.go
    - ls .
  tags:
    - docker

test:
  stage: test
  image: 'docker.gf.com.cn/docker:1.12.6'
  script:
    - env
    - docker info
  tags:
    - docker
