stages:
  - build
  - test

build:
  stage: build
  image: 'docker.gf.com.cn/go:1.8.1'
  script:
    - ln -s $(pwd) $GOPATH/src/$CI_PROJECT_NAME
    - go build
    - ls .
  tags:
    - docker

test:
  stage: test
  image: 'docker.gf.com.cn/docker:1.12.6'
  script:
    - ls .
    - docker info
  tags:
    - docker
